// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHhTH48ovOv2bCKBfSAg12G-K-48SFPAs',
    appId: '1:828142484720:web:698fac50472e6c63221635',
    messagingSenderId: '828142484720',
    projectId: 'roommate-app-2a6ab',
    authDomain: 'roommate-app-2a6ab.firebaseapp.com',
    storageBucket: 'roommate-app-2a6ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAogy566djcdLXWkoxDU2qlE_EyNjzqROM',
    appId: '1:828142484720:android:f509f5601ef03e04221635',
    messagingSenderId: '828142484720',
    projectId: 'roommate-app-2a6ab',
    storageBucket: 'roommate-app-2a6ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmuWsadGGlBtL2G1sWjJkUdmh2zUWjQM8',
    appId: '1:828142484720:ios:253d073ebee3bc83221635',
    messagingSenderId: '828142484720',
    projectId: 'roommate-app-2a6ab',
    storageBucket: 'roommate-app-2a6ab.firebasestorage.app',
    iosBundleId: 'com.example.roommateApp',
  );
}
